---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.88.18"}]

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus
  attributes:
    t3_nginx:
      ssl_certificate: wildcard.vagrant

platforms:
- name: debian-7.8
  run_list:
    - recipe[apt::default]
- name: debian-8.2
  run_list:
    - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[t3-nginx::default]
      - recipe[t3-nginx::test_default]
  - name: proxy
    run_list:
      - recipe[t3-nginx::default]
      - recipe[t3-nginx::test_proxy]
